"""
Schemas module initialization
"""
from schemas.mcp import (
    MCPServerCreate,
    MCPServerUpdate,
    MCPServerResponse,
    MCPToolResponse,
    MCPConnectResult,
    MCPServerTestResponse,
    MCPServerRefreshResponse
)

from schemas.agent_design import (
    # Bindings
    ExpressionBinding,
    StateBinding,
    # Events
    EventHandler,
    EventBinding,
    StateUpdateConfig,
    ApiCallConfig,
    # Loop & Slots
    LoopConfig,
    SlotContent,
    # Styles
    StyleConfig,
    StyleDefinition,
    # Components
    ComponentNode,
    ScriptDefinition,
    # Page
    PageSchema,
    # Requests/Responses
    SchemaUpdateRequest,
    SchemaResponse,
    ComponentAddRequest,
    ComponentUpdateRequest,
    ValidationResult,
    PreviewRequest,
    PreviewResult,
)

from schemas.common import (
    ApiResponse,
    PaginatedData,
    PaginationParams,
    ApplicationBase,
    ApplicationCreate,
    ApplicationUpdate,
    ApplicationResponse,
    ApplicationListParams,
    RunApplicationRequest,
    RunApplicationResponse,
    ConversationCreate,
    ConversationUpdate,
    ConversationListParams,
    ConversationResponse,
    MessageCreate,
    MessageResponse,
    MessageListParams,
    SkillCreate,
    SkillUpdate,
    SkillResponse,
    SkillTestRequest,
    SkillTestResponse,
    ComponentResponse,
    WSMessage,
    ChatRequest,
    StreamResponseData,
    PipelineChatRequest,
    StreamChunk,
    LoginRequest,
    RegisterRequest,
    TokenResponse,
    UserResponse
)

from schemas.agent import (
    AgentIdentity,
    AgentCapabilities,
    AgentKnowledge,
    AgentCreate,
    AgentUpdate,
    AgentResponse,
    AgentListParams,
    AgentRuntimeStatusResponse,
    agent_to_response
)

__all__ = [
    # MCP Server schemas
    "MCPServerCreate",
    "MCPServerUpdate",
    "MCPServerResponse",
    "MCPToolResponse",
    "MCPConnectResult",
    "MCPServerTestResponse",
    "MCPServerRefreshResponse",
    # Agent design schemas
    "ExpressionBinding",
    "StateBinding",
    "EventHandler",
    "EventBinding",
    "StateUpdateConfig",
    "ApiCallConfig",
    "LoopConfig",
    "SlotContent",
    "StyleConfig",
    "StyleDefinition",
    "ComponentNode",
    "ScriptDefinition",
    "PageSchema",
    "SchemaUpdateRequest",
    "SchemaResponse",
    "ComponentAddRequest",
    "ComponentUpdateRequest",
    "ValidationResult",
    "PreviewRequest",
    "PreviewResult",
    # Agent schemas
    "AgentIdentity",
    "AgentCapabilities",
    "AgentKnowledge",
    "AgentCreate",
    "AgentUpdate",
    "AgentResponse",
    "AgentListParams",
    "AgentRuntimeStatusResponse",
    "agent_to_response",
    # Common schemas
    "ApiResponse",
    "PaginatedData",
    "PaginationParams",
    "ApplicationBase",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationResponse",
    "ApplicationListParams",
    "RunApplicationRequest",
    "RunApplicationResponse",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationListParams",
    "ConversationResponse",
    "MessageCreate",
    "MessageResponse",
    "MessageListParams",
    "SkillCreate",
    "SkillUpdate",
    "SkillResponse",
    "SkillTestRequest",
    "SkillTestResponse",
    "ComponentResponse",
    "WSMessage",
    "ChatRequest",
    "StreamResponseData",
    "PipelineChatRequest",
    "StreamChunk",
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    "UserResponse",
]