"""
Schemas module initialization
"""
from schemas.mcp import (
    MCPServerCreate,
    MCPServerUpdate,
    MCPServerResponse,
    MCPToolResponse,
    MCPConnectResult
)

from schemas.common import (
    ApiResponse,
    PaginatedData,
    PaginationParams,
    ApplicationBase,
    ApplicationCreate,
    ApplicationUpdate,
    ApplicationResponse,
    ApplicationListParams,
    RunApplicationRequest,
    RunApplicationResponse,
    ConversationCreate,
    ConversationUpdate,
    ConversationListParams,
    ConversationResponse,
    MessageCreate,
    MessageResponse,
    MessageListParams,
    SkillCreate,
    SkillUpdate,
    SkillResponse,
    SkillTestRequest,
    SkillTestResponse,
    ComponentResponse,
    WSMessage,
    ChatRequest,
    StreamResponseData,
    PipelineChatRequest,
    StreamChunk,
    LoginRequest,
    RegisterRequest,
    TokenResponse,
    UserResponse
)

from schemas.agent import (
    AgentIdentity,
    AgentCapabilities,
    AgentKnowledge,
    AgentCreate,
    AgentUpdate,
    AgentResponse,
    AgentListParams,
    AgentRuntimeStatusResponse,
    agent_to_response
)

__all__ = [
    # MCP Server schemas
    "MCPServerCreate",
    "MCPServerUpdate",
    "MCPServerResponse",
    "MCPToolResponse",
    "MCPConnectResult",
    # Common schemas
    "ApiResponse",
    "PaginatedData",
    "PaginationParams",
    "ApplicationBase",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationResponse",
    "ApplicationListParams",
    "RunApplicationRequest",
    "RunApplicationResponse",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationListParams",
    "ConversationResponse",
    "MessageCreate",
    "MessageResponse",
    "MessageListParams",
    "SkillCreate",
    "SkillUpdate",
    "SkillResponse",
    "SkillTestRequest",
    "SkillTestResponse",
    "ComponentResponse",
    "WSMessage",
    "ChatRequest",
    "StreamResponseData",
    "PipelineChatRequest",
    "StreamChunk",
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    "UserResponse",
    # Agent schemas
    "AgentIdentity",
    "AgentCapabilities",
    "AgentKnowledge",
    "AgentCreate",
    "AgentUpdate",
    "AgentResponse",
    "AgentListParams",
    "AgentRuntimeStatusResponse",
    "agent_to_response",
]